export const FETCHING_BREWERIES_START = "FETCHING_BREWERIES_START";
export const FETCHING_BREWERIES_SUCCESS = "FETCHING_BREWERIES_SUCCESS";
export const FETCHING_BREWERIES_FAILURE = "FETCHING_BREWERIES_FAILURE";